@startuml

package screens {
    class Options {
        - game: HeslingtonHustle

        + Op
        tions(HeslingtonHustle)

    }

    class Playing {
        - game: HeslingtonHustle

        + Playing(game: HeslingtonHustle)


        - initTerrain(): void
        - initInteractionLocations(engine: Engine): Entity[]
        - initPlayerBody(): Fixture
        - initPlayerEntity(engine: Engine): Entity
    }

    class EndScreen {
        - MAX_DAY_SCORE: float
        - MIN_DAY_SCORE: float


        + EndScreen(game: HeslingtonHustle, endGameState: GameState)
        + getDayScore(studyCount: int, mealCount: int, recreationCount: int): float
        + calculateExamScore(days: List<GameState.Day>): float

    }
}
@enduml