on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Check format
        run: ./gradlew spotlessCheck
      - name: Test
        run: ./gradlew clean build
      - name: Upload test coverage report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: test-coverage-report
          path: tests/build/reports/jacoco/test/html/
