on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Check format
        run: ./gradlew spotlessCheck
      - name: Test
        run: ./gradlew clean build
      - if: matrix.os == 'ubuntu-latest'
        name: Upload test coverage report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: test-coverage-report
          path: tests/build/reports/jacoco/test/html/
      - if: matrix.os == 'ubuntu-latest'
        name: Upload test results
        uses: actions/upload-artifact@v4.3.3
        with:
          name: test-results
          path: tests/build/reports/tests/test/


  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: softprops/action-gh-release
        with:
          files: |
            desktop/build/libs/*.jar